
namespace ModernUI3
{
	[default_interface]
	runtimeclass ColorPickerControl : Microsoft.UI.Xaml.Controls.UserControl
	{
		ColorPickerControl();
		
		static Microsoft.UI.Xaml.DependencyProperty RProperty{ get; };
		static Microsoft.UI.Xaml.DependencyProperty GProperty{ get; };
		static Microsoft.UI.Xaml.DependencyProperty BProperty{ get; };
		static Microsoft.UI.Xaml.DependencyProperty YProperty{ get; };
		static Microsoft.UI.Xaml.DependencyProperty HeaderProperty{ get; };

		Double R;
		Double G;
		Double B;
		Double Y;

		String Header;
	}
}
